-- PROCEDIMIENTOS ALMACENADOS	
--1. CREAR SP PARA INGRESAR AL SISTEMA VALIDANDO USUARIOS Y PASSWORD
ALTER PROCEDURE USP_ACCEDER_SISTEMA
-- AQUI VA LOS PARAMETROS
@USU_LOGUEO VARCHAR(50), -- SE LE PONE CUALQUIER NOMBRE A LA VARIABLE
@PAS_LOGUEO VARCHAR(50) 
AS
BEGIN
-- AQUI VA TU CODIGO
SELECT COUNT(1) AS EXISTE
FROM TA_USUARIO WHERE 
USU_LOGUEO= @USU_LOGUEO
AND PWDCOMPARE(@PAS_LOGUEO,PAS_LOGUEO)=1

END
--PROBAR PROCEDIMIENTO ALMACENADO
EXEC USP_ACCEDER_SISTEMA 'ALEX', '1234567'

SELECT COUNT(1)
FROM TA_USUARIO WHERE 
USU_LOGUEO= 'ALEX'
AND PWDCOMPARE('123456',PAS_LOGUEO)=1 -- 1 significa que lo encontre y 0 no lo encontre 