

--PRIMERO OPCION BUSCAR PRODUCTO
-------------------------------------------------
ALTER PROCEDURE USP_BUSCAR_PRODUCTO
@COD_PRODUCTO INT= 0,
@NOM_PRODUCTO VARCHAR(50)=''
AS
BEGIN
SELECT 
COD_PRODUCTO,
NOM_PRODUCTO,
STOCK_PRODUCTO
PRE_PRODUCTO
FROM TA_PRODUCTO
WHERE (COD_PRODUCTO = @COD_PRODUCTO OR @COD_PRODUCTO = 0)
 AND NOM_PRODUCTO LIKE '%' + @NOM_PRODUCTO + '%'
END
--EXEC USP_BUSCAR_PRODUCTO 10,''

EXEC USP_BUSCAR_PRODUCTO
EXEC USP_BUSCAR_PRODUCTO 10
EXEC USP_BUSCAR_PRODUCTO 10,''

SELECT  USP_BUSCAR_PRODUCTO 10
----------------------------------------------------------------

--- AGREGAR PRODUCTO

CREATE PROCEDURE USP_AGREGAR_PRODUCTO
@NOM_PRODUCTO VARCHAR(50),
@STOCK_PRODUCTO INT,
@PRE_PRODUCTO DECIMAL(19,2)
AS
BEGIN
INSERT INTO TA_PRODUCTO
(
NOM_PRODUCTO,
STOCK_PRODUCTO,
PRE_PRODUCTO
) VALUES
(
@NOM_PRODUCTO,
@STOCK_PRODUCTO,
@PRE_PRODUCTO
)
END

SP_HELP TA_PRODUCTO
---------------------------------------------------------------