CREATE PROC USP_CREAR_USUARIO
@NOMUSU VARCHAR(50),
@PASSUSU VARCHAR(50)
AS
BEGIN
    IF EXISTS(SELECT 1
	FROM USUARIOWEB WHERE NOMUSU = @NOMUSU)BEGIN
	/*PRINT 'El usuario ya existe no puede volver a utilizar el nombtre' + @NOMUSU*/

	RAISERROR ('El usuaruo ya existe', 16, 1)
	END ELSE BEGIN

    INSERT INTO USUARIOWEB
     (NOMUSU, PASSUSU, ESTUSU)
     VALUES
     (@NOMUSU, PWDENCRYPT(@PASSUSU), 'A')

  END
END 
SELECT * FROM USUARIOWEB WHERE NOMUSU = 'ABC'
